#!/usr/bin/with-contenv bash

PERIODIC_5MIN_DIR=/etc/periodic/5min
COMMAND_EACH_5MIN="*/5   *   *   *   *   run-parts ${PERIODIC_5MIN_DIR}"

mkdir -p ${PERIODIC_5MIN_DIR}

if [ -z "$(crontab -l | grep ${PERIODIC_5MIN_DIR})" ]
then
  crontab -l > $(date --rfc-3339=date)_crontab
  sed -i 's|command$|command\nNEWLINE|g' $(date --rfc-3339=date)_crontab
  sed -i 's|^NEWLINE|'"${COMMAND_EACH_5MIN}"'|g' $(date --rfc-3339=date)_crontab
  crontab "" >> $(date --rfc-3339=date)_crontab
  crontab $(date --rfc-3339=date)_crontab
fi

exit 0